export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const UPDATE_USER_CURRENT_REQUEST = " UPDATE_USER_CURRENT_REQUEST";
export const UPDATE_USER_CURRENT_SUCCESS = "UPDATE_USER_CURRENT_SUCCESS";
export const UPDATE_USER_CURRENT_FAIL = "UPDATE_USER_CURRENT_FAIL";

export const GET_USER_SUCCESS_REQUEST = "GET_USER_SUCCESS_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const RESET_UPDATE = "RESET_UPDATE";
export const RESET_AUTH = "RESET_AUTH";

export const GET_CURRENT_USER_REQUEST = "GET_CURRENT_USER_REQUEST";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAIL = "GET_CURRENT_USER_FAIL";

export const RESET_CURRENT_USER = "RESET_CURRENT_USER";

export const RESET_ERROR_LOGIN_REGISTER = "RESET_ERROR_LOGIN_REGISTER";
