export const CREATE_SHOWTIME_REQUEST = "CREATE_SHOWTIME_REQUEST";
export const CREATE_SHOWTIME_SUCCESS = "CREATE_SHOWTIME_SUCCESS";
export const CREATE_SHOWTIME_FAIL = "CREATE_SHOWTIME_FAIL";

export const RESET_CREATE_SHOWTIME = "RESET_CREATE_SHOWTIME";


export const DELETE_SHOWTIME_REQUEST = "DELETE_SHOWTIME_REQUEST";
export const DELETE_SHOWTIME_SUCCESS = "DELETE_SHOWTIME_SUCCESS";
export const DELETE_SHOWTIME_FAIL = "DELETE_SHOWTIME_FAIL";
