export const CREATE_SHOWTIME_REQUEST = "CREATE_SHOWTIME_REQUEST";
export const CREATE_SHOWTIME_SUCCESS = "CREATE_SHOWTIME_SUCCESS";
export const CREATE_SHOWTIME_FAIL = "CREATE_SHOWTIME_FAIL";

export const RESET_CREATE_SHOWTIME = "RESET_CREATE_SHOWTIME";

export const DELETE_SHOWTIME_REQUEST = "DELETE_SHOWTIME_REQUEST";
export const DELETE_SHOWTIME_SUCCESS = "DELETE_SHOWTIME_SUCCESS";
export const DELETE_SHOWTIME_FAIL = "DELETE_SHOWTIME_FAIL";

export const GET_SHOWTIME_REQUEST = "GET_SHOWTIME_REQUEST";
export const GET_SHOWTIME_SUCCESS = "GET_SHOWTIME_SUCCESS";
export const GET_SHOWTIME_FAIL = "GET_SHOWTIME_FAIL";

export const UPDATE_SHOWTIME_REQUEST = "UPDATE_SHOWTIME_REQUEST";
export const UPDATE_SHOWTIME_SUCCESS = "UPDATE_SHOWTIME_SUCCESS";
export const UPDATE_SHOWTIME_FAIL = "UPDATE_SHOWTIME_FAIL";

// get list seat
export const GET_LISTSEAT_REQUEST = "GET_LISTSEAT_REQUEST";
export const GET_LISTSEAT_SUCCESS = "GET_LISTSEAT_SUCCESS";
export const GET_LISTSEAT_FAIL = "GET_LISTSEAT_FAIL";

// selecting seat
export const INIT_DATA = "INIT_DATA";
export const CHANGE_LISTSEAT = "CHANGE_LISTSEAT";
export const SET_DATA_PAYMENT = "SET_DATA_PAYMENT";
export const SET_READY_PAYMENT = "SET_READY_PAYMENT";
export const TIMEOUT = "TIMEOUT";
export const SET_STEP = "SET_STEP";
export const RESET_DATA_BOOKTICKET = "RESET_DATA_BOOKTICKET";
export const RESET_ALERT_OVER10 = "RESET_ALERT_OVER10";
export const SET_ALERT_OVER10 = "SET_ALERT_OVER10";

// booking ticked
export const BOOK_TICKET_REQUEST = "BOOK_TICKET_REQUEST";
export const BOOK_TICKET_SUCCESS = "BOOK_TICKET_SUCCESS";
export const BOOK_TICKET_FAIL = "BOOK_TICKET_FAIL";

export const GET_TICKET_LIST_REQUEST = "GET_TICKET_LIST_REQUEST";
export const GET_TICKET_LIST_SUCCESS = "GET_TICKET_LIST_SUCCESS";
export const GET_TICKET_LIST_FAIL = "GET_TICKET_LIST_FAIL";

export const GET_TICKET_REVENUE_REQUEST = "GET_TICKET_REVENUE_REQUEST";
export const GET_TICKET_REVENUE_SUCCESS = "GET_TICKET_REVENUE_SUCCESS";
export const GET_TICKET_REVENUE_FAIL = "GET_TICKET_REVENUE_FAIL";

export const GET_MOVIE_REVENUE_REQUEST = "GET_MOVIE_REVENUE_REQUEST";
export const GET_MOVIE_REVENUE_SUCCESS = "GET_MOVIE_REVENUE_SUCCESS";
export const GET_MOVIE_REVENUE_FAIL = "GET_MOVIE_REVENUE_FAIL";

export const GET_DAY_REVENUE_REQUEST = "GET_DAY_REVENUE_REQUEST";
export const GET_DAY_REVENUE_SUCCESS = "GET_DAY_REVENUE_SUCCESS";
export const GET_DAY_REVENUE_FAIL = "GET_DAY_REVENUE_FAIL";


export const UPDATE_UNREAD_TICKET_REQUEST = "UPDATE_UNREAD_TICKET_REQUEST";
export const UPDATE_UNREAD_TICKET_SUCCESS = "UPDATE_UNREAD_TICKET_SUCCESS";
export const UPDATE_UNREAD_TICKET_FAIL = "UPDATE_UNREAD_TICKET_FAIL";


export const RESET_SHOWTIME_DETAIL = "RESET_SHOWTIME_DETAIL";