export const GET_DISCOUNT_LIST_REQUEST = "GET_DISCOUNT_LIST_REQUEST";
export const GET_DISCOUNT_LIST_SUCCESS = "GET_DISCOUNT_LIST_SUCCESS";
export const GET_DISCOUNT_LIST_FAIL = "GET_DISCOUNT_LIST_FAIL";

export const GET_DISCOUNT_REQUEST = "GET_DISCOUNT_REQUEST";
export const GET_DISCOUNT_SUCCESS = "GET_DISCOUNT_SUCCESS";
export const GET_DISCOUNT_FAIL = "GET_DISCOUNT_FAIL";

export const UPDATE_ACTIVE_DISCOUNT_REQUEST = "UPDATE_ACTIVE_DISCOUNT_REQUEST";
export const UPDATE_ACTIVE_DISCOUNT_SUCCESS = "UPDATE_ACTIVE_DISCOUNT_SUCCESS";
export const UPDATE_ACTIVE_DISCOUNT_FAIL = "UPDATE_ACTIVE_DISCOUNT_FAIL";

export const CREATE_DISCOUNT_REQUEST = "CREATE_DISCOUNT_REQUEST";
export const CREATE_DISCOUNT_SUCCESS = "CREATE_DISCOUNT_SUCCESS";
export const CREATE_DISCOUNT_FAIL = "CREATE_DISCOUNT_FAIL";

export const DELETE_DISCOUNT_REQUEST = "DELETE_DISCOUNT_REQUEST";
export const DELETE_DISCOUNT_SUCCESS = "DELETE_DISCOUNT_SUCCESS";
export const DELETE_DISCOUNT_FAIL = "DELETE_DISCOUNT_FAIL";

export const RESET_DISCOUNT = "RESET_DISCOUNT";
export const RESET_DISCOUNT_DETAIL = "RESET_DISCOUNT_DETAIL";


