export const GET_DISCOUNT_LIST_REQUEST = "GET_DISCOUNT_LIST_REQUEST";
export const GET_DISCOUNT_LIST_SUCCESS = "GET_DISCOUNT_LIST_SUCCESS";
export const GET_DISCOUNT_LIST_FAIL = "GET_DISCOUNT_LIST_FAIL";

export const GET_DISCOUNT_REQUEST = "GET_DISCOUNT_REQUEST";
export const GET_DISCOUNT_SUCCESS = "GET_DISCOUNT_SUCCESS";
export const GET_DISCOUNT_FAIL = "GET_DISCOUNT_FAIL";

export const UPDATE_ACTIVE_DISCOUNT_REQUEST = "UPDATE_ACTIVE_DISCOUNT_REQUEST";
export const UPDATE_ACTIVE_DISCOUNT_SUCCESS = "UPDATE_ACTIVE_DISCOUNT_SUCCESS";
export const UPDATE_ACTIVE_DISCOUNT_FAIL = "UPDATE_ACTIVE_DISCOUNT_FAIL";
