export const GET_MOVIE_LIST_REQUEST = "GET_MOVIE_LIST_REQUEST";
export const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
export const GET_MOVIE_LIST_FAIL = "GET_MOVIE_LIST_FAIL";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL";

export const RESET_MOVIE_MANAGEMENT = "RESET_MOVIE_MANAGEMENT";

export const UPDATE_MOVIE_REQUEST = "POST_UPDATE_MOVIE_REQUEST";
export const UPDATE_MOVIE_SUCCESS = "POST_UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_FAIL = "POST_UPDATE_MOVIE_FAIL";
