export const GET_REVIEW_LIST_REQUEST = "GET_REVIEW_LIST_REQUEST";
export const GET_REVIEW_LIST_SUCCESS = "GET_REVIEW_LIST_SUCCESS";
export const GET_REVIEW_LIST_FAIL = "GET_REVIEW_LIST_FAIL";

export const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL";

export const LIKE_COMMENT_REQUESS = "LIKE_COMMENT_REQUESS";
export const LIKE_COMMENT_SUCCESS = "LIKE_COMMENT_SUCCESS";
export const LIKE_COMMENT_FAIL = "LIKE_COMMENT_FAIL";

