export const GET_REVIEW_LIST_REQUEST = "GET_REVIEW_LIST_REQUEST";
export const GET_REVIEW_LIST_SUCCESS = "GET_REVIEW_LIST_SUCCESS";
export const GET_REVIEW_LIST_FAIL = "GET_REVIEW_LIST_FAIL";

export const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const LIKE_COMMENT_REQUESS = "LIKE_COMMENT_REQUESS";
export const LIKE_COMMENT_SUCCESS = "LIKE_COMMENT_SUCCESS";
export const LIKE_COMMENT_FAIL = "LIKE_COMMENT_FAIL";

export const UPDATE_ACTIVE_REVIEW_REQUEST = "UPDATE_ACTIVE_REVIEW_REQUEST";
export const UPDATE_ACTIVE_REVIEW_SUCCESS = "UPDATE_ACTIVE_REVIEW_SUCCESS";
export const UPDATE_ACTIVE_REVIEW_FAIL = "UPDATE_ACTIVE_REVIEW_FAIL";

export const RESET_REVIEW_MANAGEMENT = "RESET_REVIEW_MANAGEMENT";
