export const GET_THEATER_LIST_REQUEST = "GET_THEATER_LIST_REQUEST";
export const GET_THEATER_LIST_SUCCESS = "GET_THEATER_LIST_SUCCESS";
export const GET_THEATER_LIST_FAIL = "GET_THEATER_LIST_FAIL";

export const GET_SHOWTIMES_LIST_REQUEST = "GET_SHOWTIMES_LIST_REQUEST";
export const GET_SHOWTIMES_LIST_SUCCESS = "GET_SHOWTIMES_LIST_SUCCESS";
export const GET_SHOWTIMES_LIST_FAIL = "GET_SHOWTIMES_LIST_FAIL";
