export const GET_THEATER_CLUSTER_LIST_REQUEST =
  "GET_THEATER_CLUSTER_LIST_REQUEST";
export const GET_THEATER_CLUSTER_LIST_SUCCESS =
  "GET_THEATER_CLUSTER_LIST_SUCCESS";
export const GET_THEATER_CLUSTER_LIST_FAIL = "GET_THEATER_CLUSTER_LIST_FAIL";

export const GET_THEATER_CLUSTER_REQUEST = "GET_THEATER_CLUSTER_REQUEST";
export const GET_THEATER_CLUSTER_SUCCESS = "GET_THEATER_CLUSTER_SUCCESS";
export const GET_THEATER_CLUSTER_FAIL = "GET_THEATER_CLUSTER_FAIL";

export const CREATE_THEATER_CLUSTER_REQUEST = "CREATE_THEATER_CLUSTER_REQUEST";
export const CREATE_THEATER_CLUSTER_SUCCESS = "CREATE_THEATER_CLUSTER_SUCCESS";
export const CREATE_THEATER_CLUSTER_FAIL = "CREATE_THEATER_CLUSTER_FAIL";

export const DELETE_THEATER_CLUSTER_REQUEST = "DELETE_THEATER_CLUSTER_REQUEST";
export const DELETE_THEATER_CLUSTER_SUCCESS = "DELETE_THEATER_CLUSTER_SUCCESS";
export const DELETE_THEATER_CLUSTER_FAIL = "DELETE_THEATER_CLUSTER_FAIL";

export const UPDATE_THEATER_CLUSTER_REQUEST = "UPDATE_THEATER_CLUSTER_REQUEST";
export const UPDATE_THEATER_CLUSTER_SUCCESS = "UPDATE_THEATER_CLUSTER_SUCCESS";
export const UPDATE_THEATER_CLUSTER_FAIL = "UPDATE_THEATER_CLUSTER_FAIL";

export const RESET_THEATER_CLUSTER = "RESET_THEATER_CLUSTER";

export const RESET_THEATER_CLUSTER_DETAIL = "RESET_THEATER_CLUSTER_DETAIL";
