export const GET_THEATER_SYSTEM_LIST_REQUEST =
  "GET_THEATER_SYSTEM_LIST_REQUEST";
export const GET_THEATER_SYSTEM_LIST_SUCCESS =
  "GET_THEATER_SYSTEM_LIST_SUCCESS";
export const GET_THEATER_SYSTEM_LIST_FAIL = "GET_THEATER_SYSTEM_LIST_FAIL";

export const GET_THEATER_SYSTEM_REQUEST = "GET_THEATER_SYSTEM_REQUEST";
export const GET_THEATER_SYSTEM_SUCCESS = "GET_THEATER_SYSTEM_SUCCESS";
export const GET_THEATER_SYSTEM_FAIL = "GET_THEATER_SYSTEM_FAIL";

export const GET_INFO_SHOWTIME_OF_THEATER_SYSTEM_REQUEST =
  "GET_INFO_SHOWTIME_OF_THEATER_SYSTEM_REQUEST";
export const GET_INFO_SHOWTIME_OF_THEATER_SYSTEM_SUCCES =
  "GET_INFO_SHOWTIME_OF_THEATER_SYSTEM_SUCCES";
export const GET_INFO_SHOWTIME_OF_THEATER_SYSTEM_FAIL =
  "GET_INFO_SHOWTIME_OF_THEATER_SYSTEM_FAIL";
