export const GET_THEATER_CLUSTER_LIST_REQUEST =
  "GET_THEATER_CLUSTER_LIST_REQUEST";
export const GET_THEATER_CLUSTER_LIST_SUCCESS =
  "GET_THEATER_CLUSTER_LIST_SUCCESS";
export const GET_THEATER_CLUSTER_LIST_FAIL = "GET_THEATER_CLUSTER_LIST_FAIL";


export const GET_THEATER_CLUSTER_REQUEST = "GET_THEATER_CLUSTER_REQUEST";
export const GET_THEATER_CLUSTER_SUCCESS = "GET_THEATER_CLUSTER_SUCCESS";
export const GET_THEATER_CLUSTER_FAIL = "GET_THEATER_CLUSTER_FAIL";