export const GET_THEATER_LIST_REQUEST = "GET_THEATER_LIST_REQUEST";
export const GET_THEATER_LIST_SUCCESS = "GET_THEATER_LIST_SUCCESS";
export const GET_THEATER_LIST_FAIL = "GET_THEATER_LIST_FAIL";

export const GET_SHOWTIMES_LIST_REQUEST = "GET_SHOWTIMES_LIST_REQUEST";
export const GET_SHOWTIMES_LIST_SUCCESS = "GET_SHOWTIMES_LIST_SUCCESS";
export const GET_SHOWTIMES_LIST_FAIL = "GET_SHOWTIMES_LIST_FAIL";

export const CREATE_THEATER_REQUEST = "CREATE_THEATER_REQUEST";
export const CREATE_THEATER_SUCCESS = "CREATE_THEATER_SUCCESS";
export const CREATE_THEATER_FAIL = "CREATE_THEATER_FAIL";

export const DELETE_THEATER_REQUEST = "DELETE_THEATER_REQUEST";
export const DELETE_THEATER_SUCCESS = "DELETE_THEATER_SUCCESS";
export const DELETE_THEATER_FAIL = "DELETE_THEATER_FAIL";

export const GET_THEATER_REQUEST = "GET_THEATER_REQUEST";
export const GET_THEATER_SUCCESS = "GET_THEATER_SUCCESS";
export const GET_THEATER_FAIL = "GET_THEATER_FAIL";

export const UPDATE_THEATER_REQUEST = "UPDATE_THEATER_REQUEST";
export const UPDATE_THEATER_SUCCESS = "UPDATE_THEATER_SUCCESS";
export const UPDATE_THEATER_FAIL = "UPDATE_THEATER_FAIL";

export const RESET_CREATE_THEATER = "RESET_CREATE_THEATER";
export const RESET_THEATER_DETAIL = "RESET_THEATER_DETAIL";
