export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const UPDATE_USER_CURRENT_REQUEST = " UPDATE_USER_CURRENT_REQUEST";
export const UPDATE_USER_CURRENT_SUCCESS = "UPDATE_USER_CURRENT_SUCCESS";
export const UPDATE_USER_CURRENT_FAIL = "UPDATE_USER_CURRENT_FAIL";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const RESET_UPDATE = "RESET_UPDATE";

export const RESET_ERROR_LOGIN_REGISTER = "RESET_ERROR_LOGIN_REGISTER";
